title: "JSIS / JavaScript IRC Stats"
meta_description: "JSIS is short for JavaScript IRC Stats. In short, it's a Node.js application that generates static web-pages for displaying IRC channel usage statistics. If the word \\\"IRC\\\" means nothing to you, it's quite likely this application will be completely useless for you."
meta_keywords: "JSIS JavaScript IRC Stats Statistics"

mini_magick:
  medium:
    source: images/screenshots/original/
    destination: images/screenshots/thumbs/
    resize: "212x100"


safe: false
#auto: false
server: false
server_port: 4000
baseurl: /
url: http://localhost:4000
exclude: README.md LICENSE

source: .
destination: ./_site
plugins: ./_plugins

future: true
lsi: false
pygments: true
markdown: maruku
permalink: /:categories/:year/:month/:title.html

maruku:
 use_tex: false
 use_divs: false
 png_engine: blahtex
 png_dir: images/latex
 png_url: /images/latex

rdiscount:
 extensions: []

kramdown:
 auto_ids: true,
 footnote_nr: 1
 entity_output: as_char
 toc_levels: 1..6
 use_coderay: false

 coderay:
   coderay_wrap: div
   coderay_line_numbers: inline
   coderay_line_numbers_start: 1
   coderay_tab_width: 4
   coderay_bold_every: 10
   coderay_css: style


